// Language switching functionality
let currentLang = localStorage.getItem('language') || 'ja';

// Translation data
const translations = {
    ja: {
        // Navigation
        nav_today: '本日の市況分析',
        nav_archive: '分析アーカイブ',
        nav_indicators: 'テクニカル指標解説',
        nav_terms: '市場用語集',
        nav_about: 'サイトについて',
        
        // Buttons
        login: 'ログイン',
        register: '無料登録',
        view_details: '詳細を見る',
        
        // Archive page
        archive_title: '分析アーカイブ',
        archive_subtitle: '過去の市場分析レポートを閲覧できます。日付やキーワードで検索して、必要な情報を素早く見つけましょう。',
        keyword_placeholder: 'キーワードで検索',
        select_period: '期間を選択',
        select_evaluation: '評価を選択',
        period: '期間',
        period_all: '全期間',
        period_1w: '1週間',
        period_1m: '1ヶ月',
        period_3m: '3ヶ月',
        evaluation_stats: '評価別統計',
        no_reports: '表示するレポートがありません。',
        
        // Date picker
        day_sun: '日',
        day_mon: '月',
        day_tue: '火',
        day_wed: '水',
        day_thu: '木',
        day_fri: '金',
        day_sat: '土',
        today: '今日',
        cancel: 'キャンセル',
        apply: '適用',
        
        // Select options
        select_evaluation: '評価を選択',
        
        // Evaluations
        eval_buy: '買い',
        eval_sell: '売り',
        eval_neutral: '中立',
        cases: '件',
        
        // Footer
        footer_copyright: '© 2025 Market Insight Japan. All rights reserved.',
        footer_disclaimer_short: '当サイトの情報は投資判断の参考として提供されるものであり、投資勧誘を目的としたものではありません。投資の最終判断はご自身でお願いします。',
        footer_content_title: 'コンテンツ',
        footer_site_info_title: 'サイト情報',
        footer_about_link: 'サイトについて',
        footer_analysis_method_link: '分析手法',
        footer_terms_link: '利用規約',
        footer_privacy_link: 'プライバシーポリシー',
        footer_contact_title: 'お問い合わせ',
        footer_contact_desc: 'ご質問やフィードバックがございましたら、お気軽にお問い合わせください。',
        footer_contact_button: 'お問い合わせ',
        
        // About page
        about_title: 'サイトについて',
        about_subtitle: 'YOHOU US Stock AIについて',
        about_description: '日本の短期株式トレーダー向けに、信頼性の高い市場分析を毎日2回配信するプロフェッショナルサービス',
        contact_title: 'さらに詳しい情報が必要ですか？',
        contact_description: 'YOHOU US Stock AIに関するご質問やご不明点がございましたら、お気軽にお問い合わせください。専門スタッフが丁寧にお答えします。',
        contact_form: 'お問い合わせフォーム',
        trial_button: '無料トライアルに申し込む',
        
        // Main page
        main_title: 'S&P 500 インタラクティブ市場分析',
        main_subtitle: '短期トレーダーのためのデータ駆動型インサイト',
        summary_title: '総合評価',
        
        // Terms page
        terms_title: '市場用語集',
        terms_subtitle: '株式市場で使用される専門用語を解説します。基本用語からチャート用語、指標用語、取引用語まで、投資家のレベルに合わせた情報を提供します。',
        search_placeholder: '用語を検索',
        terms_imp_high: '重要度高',
        terms_imp_medium: '重要度中',
        terms_imp_low: '重要度低',
        terms_cat_all: 'すべて',
        terms_cat_basic: '基本用語',
        terms_cat_chart: 'チャート用語',
        terms_cat_indicator: '指標用語',
        terms_cat_trading: '取引用語',
        terms_sidebar_kana_index: '五十音順',
        terms_sidebar_kana_en: '英数',
        terms_sidebar_categories: 'カテゴリー',
        terms_sidebar_cat_all: 'すべての用語',
        terms_sidebar_frequent_terms: 'よく検索される用語',
        terms_ipo_short_desc: '新規株式公開',
        terms_per_short_desc: '株価収益率',
        terms_pbr_short_desc: '株価純資産倍率',
        terms_volume_title: '出来高',
        terms_volume_short_desc: '取引量の指標',
        terms_section_en: '英数',
        terms_section_a: 'あ行',
        terms_section_ka: 'か行',
        terms_section_sa: 'さ行',
        terms_section_ta: 'た行',
        terms_section_na: 'な行',
        terms_section_ha: 'は行',
        terms_section_ma: 'ま行',
        terms_section_ya: 'や行',
        terms_section_ra: 'ら行',
        terms_section_wa: 'わ行',
        terms_reusable_main_points: '主なポイント',
        terms_reusable_calculation: '計算方法',
        terms_reusable_example: '使用例',
        terms_reusable_related: '関連用語',
        term_ipo_title: 'IPO（新規株式公開）',
        term_ipo_desc: 'IPO（Initial Public Offering）とは、未上場企業が新たに株式を証券取引所に上場し、公開することです。企業は資金調達を行い、投資家は新たな投資機会を得ることができます。',
        term_ipo_point1: '企業が資金調達を行う重要な手段',
        term_ipo_point2: '株式の公開価格は主幹事証券会社によって決定される',
        term_ipo_point3: '抽選方式で一般投資家に割り当てられることが多い',
        term_ipo_point4: '上場初日は価格変動が大きくなる傾向がある',
        term_ipo_example: '「テクノロジー企業Aは来月IPOを予定しており、初値は公開価格を大きく上回ると予想されている」',
        term_ipo_related1: 'ブックビルディング',
        term_ipo_related2: '上場',
        term_ipo_related3: '時価総額',
        term_per_title: 'PER（株価収益率）',
        term_per_desc: 'PER（Price Earnings Ratio）は、株価を1株当たりの純利益（EPS）で割った値で、株価が収益の何倍かを示す指標です。企業の株価が割高か割安かを判断する際に使用されます。',
        term_per_formula: 'PER = 株価 ÷ 1株当たり純利益（EPS）',
        term_per_formula_example: '例：株価が3,000円、EPSが150円の場合、PERは20倍',
        term_per_example: '「この企業のPERは30倍と業界平均の20倍を大きく上回っており、株価が割高な可能性がある」',
        term_per_related1: 'PBR',
        term_per_related2: 'EPS',
        term_per_related3: 'ROE',
        term_pbr_title: 'PBR（株価純資産倍率）',
        term_pbr_desc: 'PBR（Price Book-value Ratio）は、株価を1株当たりの純資産（BPS）で割った値で、株価が純資産の何倍かを示す指標です。企業の資産価値に対する株価の割高・割安を判断する際に使用されます。',
        term_pbr_formula: 'PBR = 株価 ÷ 1株当たり純資産（BPS）',
        term_pbr_formula_example: '例：株価が3,000円、BPSが2,000円の場合、PBRは1.5倍',
        term_pbr_example: '「この企業のPBRは0.8倍と1倍を下回っており、純資産に対して株価が割安な状態にある」',
        term_pbr_related1: 'PER',
        term_pbr_related2: 'BPS',
        term_pbr_related3: '純資産',
        term_roe_title: 'ROE（自己資本利益率）',
        term_roe_desc: 'ROE（Return On Equity）は、企業の自己資本（株主資本）に対する当期純利益の割合を示す指標です。企業が株主から預かった資本をどれだけ効率的に利益に変換しているかを測定します。',
        term_roe_formula: 'ROE = 当期純利益 ÷ 自己資本 × 100（%）',
        term_roe_formula_example: '例：当期純利益が100億円、自己資本が1,000億円の場合、ROEは10%',
        term_roe_example: '「この企業のROEは15%と高く、株主資本を効率的に活用して利益を生み出している」',
        term_roe_related1: 'ROA',
        term_roe_related2: 'EPS',
        term_roe_related3: '自己資本',
        term_low_price_title: '安値（やすね）',
        term_low_price_desc: '安値とは、一定期間内における株価の最も低い価格のことを指します。日中安値、年初来安値、史上最安値など、参照する期間によって異なります。',
        term_low_price_point1: 'テクニカル分析において重要なサポートレベルとなることが多い',
        term_low_price_point2: '連続して安値を更新する場合は下降トレンドの強さを示す',
        term_low_price_point3: '前回の安値を割り込まずに反発する場合は、底打ちのサインとなることがある',
        term_low_price_point4: '年初来安値や史上最安値の更新は、投資家心理に大きな影響を与える',
        term_low_price_example: '「日経平均は一時27,000円の年初来安値を記録したが、その後は反発して上昇トレンドに転じた」',
        term_low_price_related1: '高値',
        term_low_price_related2: 'サポートライン',
        term_low_price_related3: '底値',
        term_uptrend_title: 'アップトレンド',
        term_uptrend_desc: 'アップトレンドとは、株価が全体的に上昇傾向にある状態を指します。高値と安値がともに切り上がっていく（前回の高値より高い高値、前回の安値より高い安値をつける）パターンが特徴です。',
        term_uptrend_point1: '高値と安値が切り上がりながら推移する',
        term_uptrend_point2: '移動平均線が上昇傾向を示し、株価が移動平均線の上に位置することが多い',
        term_uptrend_point3: '調整（一時的な下落）後も、前回の安値を割り込まずに上昇を再開する',
        term_uptrend_point4: '出来高は上昇局面で増加し、調整局面で減少する傾向がある',
        term_uptrend_example: '「この銘柄は3ヶ月間アップトレンドが続いており、押し目買いの好機を狙っている投資家が多い」',
        term_uptrend_related1: 'ダウントレンド',
        term_uptrend_related2: 'レンジ相場',
        term_uptrend_related3: 'トレンドライン',
        term_stock_index_title: '株価指数（かぶかしすう）',
        term_stock_index_desc: '株価指数とは、特定の市場や業種の株価全体の動向を表す指標です。複数の銘柄の株価を一定のルールで集計し、単一の数値として表します。市場全体の動きを把握するために使用されます。',
        term_stock_index_point1: '日経平均株価（日経225）：東証一部上場企業から選ばれた225銘柄の平均株価',
        term_stock_index_point2: 'TOPIX（東証株価指数）：東証一部上場全銘柄の時価総額加重平均',
        term_stock_index_point3: 'JPX日経インデックス400：ROEなどの指標を基に選定された400銘柄の時価総額加重平均',
        term_stock_index_point4: '日経ジャスダック平均：ジャスダック市場上場銘柄の平均株価',
        term_stock_index_example: '「本日の日経平均株価は前日比300円高の29,500円で取引を終えた」',
        term_stock_index_related1: '日経平均',
        term_stock_index_related2: 'TOPIX',
        term_stock_index_related3: '指数化',
        term_shareholder_benefit_title: '株主優待（かぶぬしゆうたい）',
        term_shareholder_benefit_desc: '株主優待とは、企業が自社株主に対して提供する特典のことです。自社製品、商品券、割引券などが一般的で、配当とは別に株主に還元する仕組みです。',
        term_shareholder_benefit_point1: '権利確定日に株主名簿に記載されている株主に付与される',
        term_shareholder_benefit_point2: '保有株数に応じて優待内容が異なることが多い',
        term_shareholder_benefit_point3: '年1回または年2回実施する企業が多い',
        term_shareholder_benefit_point4: '長期保有株主向けの特別優待を設ける企業も増えている',
        term_shareholder_benefit_example: '「この飲食チェーンは100株以上保有する株主に対して、年2回5,000円相当の食事券を株主優待として提供している」',
        term_shareholder_benefit_related1: '配当',
        term_shareholder_benefit_related2: '権利確定日',
        term_shareholder_benefit_related3: '株主還元',
        term_stock_split_title: '株式分割（かぶしきぶんかつ）',
        term_stock_split_desc: '株式分割とは、企業が発行済み株式を分割して株式数を増やす手法です。株主が保有する株式数は増えますが、株価は分割比率に応じて下がるため、理論上は資産価値は変わりません。',
        term_stock_split_point1: '1株を2株、1株を3株など、様々な分割比率がある',
        term_stock_split_point2: '株価が高騰した銘柄の投資しやすさを向上させる目的で実施されることが多い',
        term_stock_split_point3: '株式の流動性向上につながる',
        term_stock_split_point4: '分割による株価の調整後、心理的に割安感が生まれ株価が上昇することもある',
        term_stock_split_example: '「テクノロジー企業Bは来月1:4の株式分割を実施し、現在の株価40,000円を10,000円程度に調整する予定だ」',
        term_stock_split_related1: '株式併合',
        term_stock_split_related2: '権利落ち',
        term_stock_split_related3: 'EPS',
        term_support_line_title: 'サポートライン',
        term_support_line_desc: 'サポートラインとは、チャート上で株価が下落した際に反発しやすい価格帯を結んだラインのことです。過去に何度か株価が反発した価格水準に引かれ、下値支持線とも呼ばれます。',
        term_support_line_point1: '過去の安値を結ぶことで形成される',
        term_support_line_point2: '株価がサポートラインに接近すると買い注文が入りやすい',
        term_support_line_point3: 'サポートラインを下抜けると、さらなる下落の可能性が高まる',
        term_support_line_point4: '下抜けた後に再び上抜けると、レジスタンスラインに転換することがある',
        term_support_line_example: '「日経平均は28,000円付近に強いサポートラインがあり、3度この水準で反発している」',
        term_support_line_related1: 'レジスタンスライン',
        term_support_line_related2: 'トレンドライン',
        term_support_line_related3: 'ブレイクアウト',
        term_limit_order_title: '指値注文（さしねちゅうもん）',
        term_limit_order_desc: '指値注文とは、株式の売買において、取引を行う価格を指定する注文方法です。買いの場合は指定価格以下、売りの場合は指定価格以上でないと約定しません。',
        term_limit_order_point1: '希望する価格で取引できるというメリットがある',
        term_limit_order_point2: '指定した価格に到達しない場合は約定しないリスクがある',
        term_limit_order_point3: '価格変動が激しい相場では約定しにくくなることがある',
        term_limit_order_point4: '寄り付き（取引開始時）や引け（取引終了時）に特殊な指値注文方法がある',
        term_limit_order_example: '「現在の株価は1,500円だが、1,450円で指値買い注文を出しておき、一時的な下落時に自動的に買えるようにした」',
        term_limit_order_related1: '成行注文',
        term_limit_order_related2: '逆指値注文',
        term_limit_order_related3: 'IOC注文',
        term_high_price_title: '高値（たかね）',
        term_high_price_desc: '高値とは、一定期間内における株価の最も高い価格のことを指します。日中高値、年初来高値、史上最高値など、参照する期間によって異なります。',
        term_high_price_point1: 'テクニカル分析において重要なレジスタンスレベルとなることが多い',
        term_high_price_point2: '連続して高値を更新する場合は上昇トレンドの強さを示す',
        term_high_price_point3: '前回の高値を超えられずに反落する場合は、天井のサインとなることがある',
        term_high_price_point4: '年初来高値や史上最高値の更新は、投資家心理に大きな影響を与える',
        term_high_price_example: '「日経平均は一時30,000円の年初来高値を記録したが、その後は利益確定売りで反落した」',
        term_high_price_related1: '安値',
        term_high_price_related2: 'レジスタンスライン',
        term_high_price_related3: '天井',
        term_downtrend_title: 'ダウントレンド',
        term_downtrend_desc: 'ダウントレンドとは、株価が全体的に下落傾向にある状態を指します。高値と安値がともに切り下がっていく（前回の高値より低い高値、前回の安値より低い安値をつける）パターンが特徴です。',
        term_downtrend_point1: '高値と安値が切り下がりながら推移する',
        term_downtrend_point2: '移動平均線が下降傾向を示し、株価が移動平均線の下に位置することが多い',
        term_downtrend_point3: '反発（一時的な上昇）後も、前回の高値を超えずに下落を再開する',
        term_downtrend_point4: '出来高は下落局面で増加し、反発局面で減少する傾向がある',
        term_downtrend_example: '「この銘柄は2ヶ月間ダウントレンドが続いており、反発を売る戦略が有効となっている」',
        term_downtrend_related1: 'アップトレンド',
        term_downtrend_related2: 'レンジ相場',
        term_downtrend_related3: 'トレンドライン',
        term_nikkei_title: '日経平均株価（にっけいへいきんかぶか）',
        term_nikkei_desc: '日経平均株価（日経225）は、東京証券取引所に上場する代表的な225銘柄の株価を平均した指数です。日本の株式市場全体の動向を示す代表的な指標として広く利用されています。',
        term_nikkei_point1: '株価平均型の指数で、株価の高い銘柄ほど影響力が大きい',
        term_nikkei_point2: '日本経済新聞社が算出・公表している',
        term_nikkei_point3: '構成銘柄は定期的に見直される',
        term_nikkei_point4: '先物やオプション取引の対象となっている',
        term_nikkei_example: '「米国株式市場の上昇を受けて、日経平均株価は29,000円台を回復した」',
        term_nikkei_related1: 'TOPIX',
        term_nikkei_related2: 'ダウ平均',
        term_nikkei_related3: '日経平均先物',
        term_dividend_title: '配当（はいとう）',
        term_dividend_desc: '配当とは、企業が利益の一部を株主に現金で還元する仕組みです。株主に対する重要な利益還元方法の一つで、通常は年1回（期末配当）または年2回（中間配当と期末配当）実施されます。',
        term_dividend_point1: '配当金額は1株あたりの金額で表示される',
        term_dividend_point2: '配当利回り = 年間配当金 ÷ 株価 × 100（%）で計算される',
        term_dividend_point3: '権利確定日に株主名簿に記載されている株主に支払われる',
        term_dividend_point4: '配当性向 = 配当金総額 ÷ 当期純利益 × 100（%）で、利益に対する配当の割合を示す',
        term_dividend_example: '「この企業は1株あたり年間60円の配当を実施しており、現在の株価3,000円に対して配当利回りは2%となる」',
        term_dividend_related1: '配当利回り',
        term_dividend_related2: '権利確定日',
        term_dividend_related3: '株主還元',
        term_gap_title: '窓（まど）/ ギャップ',
        term_gap_desc: '窓（ギャップ）とは、前日の終値と当日の始値の間に価格の空白部分ができる現象です。上昇ギャップ（前日終値より高い始値）と下落ギャップ（前日終値より低い始値）があります。',
        term_gap_point1: '重要な経済指標の発表や企業の決算発表後などに発生しやすい',
        term_gap_point2: '「窓は埋まる」という格言があり、後日その価格帯まで戻ることが多い',
        term_gap_point3: '上昇トレンド中の上昇ギャップは強気サイン、下降トレンド中の下落ギャップは弱気サイン',
        term_gap_point4: '大きなギャップが発生した場合、トレンド転換のサインとなることがある',
        term_gap_example: '「好決算を受けて、この銘柄は前日終値の1,500円から当日始値1,580円と大きな上昇ギャップで取引を開始した」',
        term_gap_related1: '窓埋め',
        term_gap_related2: '寄り付き',
        term_gap_related3: '前日比',
        term_ohlc_title: '四本値（よんほんち）',
        term_ohlc_desc: '四本値とは、一定期間（通常は1日）の株価を表す4つの値段のことで、始値、高値、安値、終値を指します。ローソク足チャートの基本となる価格情報です。',
        term_ohlc_point1: '始値：取引開始時の最初の約定価格',
        term_ohlc_point2: '高値：期間内の最も高い取引価格',
        term_ohlc_point3: '安値：期間内の最も低い取引価格',
        term_ohlc_point4: '終値：取引終了時の最後の約定価格（翌日の基準価格となる）',
        term_ohlc_example: '「本日のトヨタ自動車の四本値は、始値2,100円、高値2,150円、安値2,080円、終値2,120円だった」',
        term_ohlc_related1: 'ローソク足',
        term_ohlc_related2: '寄り付き',
        term_ohlc_related3: '引け',
        term_candlestick_title: 'ローソク足',
        term_candlestick_desc: 'ローソク足とは、株価の動きを視覚的に表現するチャート手法で、日本発祥のテクニカル分析ツールです。始値、高値、安値、終値の四本値を一つの図形で表現します。',
        term_candlestick_point1: '実体（ボディ）：始値と終値を結んだ長方形部分',
        term_candlestick_point2: 'ヒゲ（シャドウ）：高値・安値から実体までの線',
        term_candlestick_point3: '陽線（白/緑/青）：終値が始値より高い場合（上昇）',
        term_candlestick_point4: '陰線（黒/赤）：終値が始値より低い場合（下落）',
        term_candlestick_point5: '様々なパターン（はらみ線、包み線、十字線など）が相場の転換点を示す',
        term_candlestick_example: '「日足チャートで3本連続の大陽線が現れ、強い買い圧力が続いていることを示している」',
        term_candlestick_related1: '四本値',
        term_candlestick_related2: '陽線',
        term_candlestick_related3: '陰線',
        term_resistance_line_title: 'レジスタンスライン',
        term_resistance_line_desc: 'レジスタンスラインとは、チャート上で株価が上昇した際に反落しやすい価格帯を結んだラインのことです。過去に何度か株価が反落した価格水準に引かれ、上値抵抗線とも呼ばれます。',
        term_resistance_line_point1: '過去の高値を結ぶことで形成される',
        term_resistance_line_point2: '株価がレジスタンスラインに接近すると売り注文が入りやすい',
        term_resistance_line_point3: 'レジスタンスラインを上抜けると、さらなる上昇の可能性が高まる',
        term_resistance_line_point4: '上抜けた後に再び下抜けると、サポートラインに転換することがある',
        term_resistance_line_example: '「日経平均は30,000円付近に強いレジスタンスラインがあり、2度この水準で反落している」',
        term_resistance_line_related1: 'サポートライン',
        term_resistance_line_related2: 'トレンドライン',
        term_resistance_line_related3: 'ブレイクアウト',
        term_value_stock_title: '割安株（わりやすかぶ）',
        term_value_stock_desc: '割安株とは、企業の本来の価値（理論価値や適正価値）に比べて株価が割安に評価されていると考えられる株式のことです。バリュー投資の対象となります。',
        term_value_stock_point1: 'PER（株価収益率）が業界平均や市場平均より低い',
        term_value_stock_point2: 'PBR（株価純資産倍率）が1倍を下回る、または業界平均より低い',
        term_value_stock_point3: '配当利回りが市場平均より高い',
        term_value_stock_point4: '企業の成長性や収益性に対して株価が割安に放置されている状態',
        term_value_stock_example: '「この銀行株はPBR0.6倍、配当利回り4%と典型的な割安株の特徴を示している」',
        term_value_stock_related1: '割高株',
        term_value_stock_related2: 'バリュー投資',
        term_value_stock_related3: 'PER',

        // Indicators page
        indicators_title: 'テクニカル指標解説',
        indicators_subtitle: '主要なテクニカル指標の詳細解説',
        indicator_search_placeholder: '指標名で検索'
    },
    en: {
        // Navigation
        nav_today: 'Today\'s Market Analysis',
        nav_archive: 'Analysis Archive',
        nav_indicators: 'Technical Indicators',
        nav_terms: 'Market Terms',
        nav_about: 'About',
        
        // Buttons
        login: 'Login',
        register: 'Free Registration',
        view_details: 'View Details',
        
        // Archive page
        archive_title: 'Analysis Archive',
        archive_subtitle: 'Browse past market analysis reports. Search by date or keywords to quickly find the information you need.',
        keyword_placeholder: 'Search by keyword',
        select_period: 'Select Period',
        select_evaluation: 'Select Evaluation',
        period: 'Period',
        period_all: 'All Periods',
        period_1w: '1 Week',
        period_1m: '1 Month',
        period_3m: '3 Months',
        evaluation_stats: 'Evaluation Statistics',
        no_reports: 'No reports to display.',
        
        // Date picker
        day_sun: 'Sun',
        day_mon: 'Mon',
        day_tue: 'Tue',
        day_wed: 'Wed',
        day_thu: 'Thu',
        day_fri: 'Fri',
        day_sat: 'Sat',
        today: 'Today',
        cancel: 'Cancel',
        apply: 'Apply',
        
        // Select options
        select_evaluation: 'Select Evaluation',
        
        // Evaluations
        eval_buy: 'Buy',
        eval_sell: 'Sell',
        eval_neutral: 'Neutral',
        cases: 'cases',
        
        // Footer
        footer_copyright: '© 2025 Market Insight Japan. All rights reserved.',
        footer_disclaimer_short: 'The information on this site is provided for reference purposes for investment decisions and is not intended as a solicitation for investment. Please make your own final investment decisions.',
        footer_content_title: 'Content',
        footer_site_info_title: 'Site Information',
        footer_about_link: 'About',
        footer_analysis_method_link: 'Analysis Method',
        footer_terms_link: 'Terms of Use',
        footer_privacy_link: 'Privacy Policy',
        footer_contact_title: 'Contact',
        footer_contact_desc: 'If you have any questions or feedback, please feel free to contact us.',
        footer_contact_button: 'Contact Us',

        // About page
        about_title: 'About',
        about_subtitle: 'About YOHOU US Stock AI',
        about_description: 'A professional service that delivers reliable market analysis twice daily for Japanese short-term stock traders',
        contact_title: 'Need more detailed information?',
        contact_description: 'If you have any questions or concerns about YOHOU US Stock AI, please feel free to contact us. Our specialist staff will answer you politely.',
        contact_form: 'Contact Form',
        trial_button: 'Apply for Free Trial',
        
        // Main page
        main_title: 'S&P 500 Interactive Market Analysis',
        main_subtitle: 'Data-driven insights for short-term traders',
        summary_title: 'Overall Assessment',
        
        // Terms page
        terms_title: 'Market Glossary',
        terms_subtitle: 'Explains specialized terms used in the stock market. Provides information tailored to investor levels, from basic and chart terms to indicator and trading terms.',
        search_placeholder: 'Search for terms',
        terms_imp_high: 'High Importance',
        terms_imp_medium: 'Medium Importance',
        terms_imp_low: 'Low Importance',
        terms_cat_all: 'All',
        terms_cat_basic: 'Basic Terms',
        terms_cat_chart: 'Chart Terms',
        terms_cat_indicator: 'Indicator Terms',
        terms_cat_trading: 'Trading Terms',
        terms_sidebar_kana_index: 'Alphabetical Index',
        terms_sidebar_kana_en: 'A-Z',
        terms_sidebar_categories: 'Categories',
        terms_sidebar_cat_all: 'All Terms',
        terms_sidebar_frequent_terms: 'Frequently Searched',
        terms_ipo_short_desc: 'Initial Public Offering',
        terms_per_short_desc: 'Price Earnings Ratio',
        terms_pbr_short_desc: 'Price Book-value Ratio',
        terms_volume_title: 'Volume',
        terms_volume_short_desc: 'Indicator of trading volume',
        terms_section_en: 'A-Z',
        terms_section_a: 'A-line',
        terms_section_ka: 'Ka-line',
        terms_section_sa: 'Sa-line',
        terms_section_ta: 'Ta-line',
        terms_section_na: 'Na-line',
        terms_section_ha: 'Ha-line',
        terms_section_ma: 'Ma-line',
        terms_section_ya: 'Ya-line',
        terms_section_ra: 'Ra-line',
        terms_section_wa: 'Wa-line',
        terms_reusable_main_points: 'Main Points',
        terms_reusable_calculation: 'Calculation Method',
        terms_reusable_example: 'Usage Example',
        terms_reusable_related: 'Related Terms',
        term_ipo_title: 'IPO (Initial Public Offering)',
        term_ipo_desc: 'An IPO (Initial Public Offering) is when a private company lists its shares on a stock exchange for the first time, making them available for public purchase. This allows the company to raise capital and provides investors with a new investment opportunity.',
        term_ipo_point1: 'An important means for companies to raise capital.',
        term_ipo_point2: 'The offering price is determined by the lead underwriting securities company.',
        term_ipo_point3: 'Shares are often allocated to retail investors through a lottery system.',
        term_ipo_point4: 'The stock price tends to be highly volatile on the first day of trading.',
        term_ipo_example: '"Tech Company A is scheduled for an IPO next month, and its initial price is expected to be significantly higher than the offering price."',
        term_ipo_related1: 'Book Building',
        term_ipo_related2: 'Listing',
        term_ipo_related3: 'Market Capitalization',
        term_per_title: 'PER (Price Earnings Ratio)',
        term_per_desc: 'PER (Price Earnings Ratio) is a metric that measures a company\'s stock price relative to its earnings per share (EPS). It is used to assess whether a company\'s stock is overvalued or undervalued.',
        term_per_formula: 'PER = Stock Price ÷ Earnings Per Share (EPS)',
        term_per_formula_example: 'e.g., If stock price is ¥3,000 and EPS is ¥150, the PER is 20x.',
        term_per_example: '"This company\'s PER of 30x is significantly higher than the industry average of 20x, suggesting the stock may be overvalued."',
        term_per_related1: 'PBR',
        term_per_related2: 'EPS',
        term_per_related3: 'ROE',
        term_pbr_title: 'PBR (Price Book-value Ratio)',
        term_pbr_desc: 'PBR (Price Book-value Ratio) is a metric that compares a company\'s stock price to its book value per share (BPS). It is used to assess whether a stock is overvalued or undervalued relative to its asset value.',
        term_pbr_formula: 'PBR = Stock Price ÷ Book Value Per Share (BPS)',
        term_pbr_formula_example: 'e.g., If stock price is ¥3,000 and BPS is ¥2,000, the PBR is 1.5x.',
        term_pbr_example: '"This company\'s PBR of 0.8x is below 1, indicating that the stock is undervalued relative to its net assets."',
        term_pbr_related1: 'PER',
        term_pbr_related2: 'BPS',
        term_pbr_related3: 'Net Assets',
        term_roe_title: 'ROE (Return On Equity)',
        term_roe_desc: 'ROE (Return On Equity) is a metric that shows the ratio of a company\'s net income to its shareholders\' equity. It measures how efficiently the company is using capital from shareholders to generate profits.',
        term_roe_formula: 'ROE = Net Income ÷ Shareholders\' Equity × 100 (%)',
        term_roe_formula_example: 'e.g., If net income is ¥10 billion and shareholders\' equity is ¥100 billion, the ROE is 10%.',
        term_roe_example: '"This company has a high ROE of 15%, indicating it is using shareholder capital efficiently to generate profits."',
        term_roe_related1: 'ROA',
        term_roe_related2: 'EPS',
        term_roe_related3: 'Shareholders\' Equity',
        term_low_price_title: 'Low Price',
        term_low_price_desc: 'The low price refers to the lowest stock price within a specific period. It varies depending on the reference period, such as intraday low, year-to-date low, or all-time low.',
        term_low_price_point1: 'Often serves as a key support level in technical analysis.',
        term_low_price_point2: 'Consecutive new lows indicate a strong downward trend.',
        term_low_price_point3: 'A rebound without breaking the previous low can be a sign of bottoming out.',
        term_low_price_point4: 'New year-to-date or all-time lows significantly impact investor sentiment.',
        term_low_price_example: '"The Nikkei Average briefly hit a year-to-date low of ¥27,000 before rebounding into an uptrend."',
        term_low_price_related1: 'High Price',
        term_low_price_related2: 'Support Line',
        term_low_price_related3: 'Bottom Price',
        term_uptrend_title: 'Uptrend',
        term_uptrend_desc: 'An uptrend describes a situation where a stock price is generally moving upward. It is characterized by a pattern of higher highs and higher lows.',
        term_uptrend_point1: 'Characterized by a series of higher highs and higher lows.',
        term_uptrend_point2: 'The moving average trends upward, and the price often stays above it.',
        term_uptrend_point3: 'After a temporary decline (correction), the uptrend resumes without breaking the previous low.',
        term_uptrend_point4: 'Volume tends to increase during upward movements and decrease during corrections.',
        term_uptrend_example: '"This stock has been in an uptrend for three months, and many investors are looking for opportunities to buy on dips."',
        term_uptrend_related1: 'Downtrend',
        term_uptrend_related2: 'Ranging Market',
        term_uptrend_related3: 'Trendline',
        term_stock_index_title: 'Stock Index',
        term_stock_index_desc: 'A stock index represents the overall performance of a specific market or sector. It is calculated by aggregating the prices of multiple stocks according to a set formula, providing a single value to track market movements.',
        term_stock_index_point1: 'Nikkei Stock Average (Nikkei 225): An average of 225 stocks selected from the TSE First Section.',
        term_stock_index_point2: 'TOPIX (Tokyo Stock Price Index): A market capitalization-weighted average of all stocks on the TSE First Section.',
        term_stock_index_point3: 'JPX-Nikkei Index 400: A market capitalization-weighted average of 400 stocks selected based on metrics like ROE.',
        term_stock_index_point4: 'Nikkei Jasdaq Average: An average of stocks listed on the Jasdaq market.',
        term_stock_index_example: '"Today, the Nikkei Stock Average closed at ¥29,500, up ¥300 from the previous day."',
        term_stock_index_related1: 'Nikkei Average',
        term_stock_index_related2: 'TOPIX',
        term_stock_index_related3: 'Indexing',
        term_shareholder_benefit_title: 'Shareholder Benefits',
        term_shareholder_benefit_desc: 'Shareholder benefits are perks offered by a company to its shareholders. These typically include company products, gift certificates, or discounts, and are a way of returning value to shareholders in addition to dividends.',
        term_shareholder_benefit_point1: 'Granted to shareholders listed on the company register on the record date.',
        term_shareholder_benefit_point2: 'The type of benefit often varies based on the number of shares held.',
        term_shareholder_benefit_point3: 'Most companies offer them once or twice a year.',
        term_shareholder_benefit_point4: 'An increasing number of companies are offering special benefits for long-term shareholders.',
        term_shareholder_benefit_example: '"This restaurant chain offers its shareholders with 100 or more shares a ¥5,000 meal voucher twice a year as a benefit."',
        term_shareholder_benefit_related1: 'Dividend',
        term_shareholder_benefit_related2: 'Record Date',
        term_shareholder_benefit_related3: 'Shareholder Return',
        term_stock_split_title: 'Stock Split',
        term_stock_split_desc: 'A stock split is a corporate action where a company divides its existing shares into multiple shares to boost liquidity. While the number of shares increases, the price per share decreases proportionally, so the total value of an investor\'s holdings remains the same.',
        term_stock_split_point1: 'Splits can have various ratios, such as 2-for-1 or 3-for-1.',
        term_stock_split_point2: 'Often performed to make a high-priced stock more accessible to investors.',
        term_stock_split_point3: 'Leads to increased stock liquidity.',
        term_stock_split_point4: 'The lower post-split price can create a perception of being a bargain, sometimes leading to a price increase.',
        term_stock_split_example: '"Tech Company B will execute a 1-for-4 stock split next month, adjusting its current ¥40,000 stock price to around ¥10,000."',
        term_stock_split_related1: 'Reverse Stock Split',
        term_stock_split_related2: 'Ex-Dividend',
        term_stock_split_related3: 'EPS',
        term_support_line_title: 'Support Line',
        term_support_line_desc: 'A support line is a level on a chart where a falling stock price tends to pause or rebound. It is formed by connecting previous lows and is also known as a support level.',
        term_support_line_point1: 'Formed by connecting past low points.',
        term_support_line_point2: 'Buying interest tends to increase as the price approaches a support line.',
        term_support_line_point3: 'A break below the support line suggests a higher probability of further decline.',
        term_support_line_point4: 'A former support line can become a resistance line if the price breaks below and then returns to it.',
        term_support_line_example: '"The Nikkei Average has strong support around ¥28,000, having rebounded from this level three times."',
        term_support_line_related1: 'Resistance Line',
        term_support_line_related2: 'Trendline',
        term_support_line_related3: 'Breakout',
        term_limit_order_title: 'Limit Order',
        term_limit_order_desc: 'A limit order is a type of order to buy or sell a stock at a specified price or better. A buy limit order is executed only at the limit price or lower, and a sell limit order is executed only at the limit price or higher.',
        term_limit_order_point1: 'The main advantage is that you can trade at your desired price.',
        term_limit_order_point2: 'There is a risk the order will not be executed if the price does not reach the specified level.',
        term_limit_order_point3: 'Execution can be difficult in highly volatile markets.',
        term_limit_order_point4: 'Special types of limit orders exist for market open and close.',
        term_limit_order_example: '"The current stock price is ¥1,500, but I placed a limit buy order at ¥1,450 to automatically purchase it on a temporary dip."',
        term_limit_order_related1: 'Market Order',
        term_limit_order_related2: 'Stop Order',
        term_limit_order_related3: 'IOC Order',
        term_high_price_title: 'High Price',
        term_high_price_desc: 'The high price refers to the highest stock price within a specific period. It varies depending on the reference period, such as intraday high, year-to-date high, or all-time high.',
        term_high_price_point1: 'Often serves as a key resistance level in technical analysis.',
        term_high_price_point2: 'Consecutive new highs indicate a strong upward trend.',
        term_high_price_point3: 'Failure to surpass a previous high can be a sign of a top.',
        term_high_price_point4: 'New year-to-date or all-time highs significantly impact investor sentiment.',
        term_high_price_example: '"The Nikkei Average briefly hit a year-to-date high of ¥30,000 before falling back on profit-taking."',
        term_high_price_related1: 'Low Price',
        term_high_price_related2: 'Resistance Line',
        term_high_price_related3: 'Ceiling',
        term_downtrend_title: 'Downtrend',
        term_downtrend_desc: 'A downtrend describes a situation where a stock price is generally moving downward. It is characterized by a pattern of lower highs and lower lows.',
        term_downtrend_point1: 'Characterized by a series of lower highs and lower lows.',
        term_downtrend_point2: 'The moving average trends downward, and the price often stays below it.',
        term_downtrend_point3: 'After a temporary rise (rebound), the downtrend resumes without exceeding the previous high.',
        term_downtrend_point4: 'Volume tends to increase during downward movements and decrease during rebounds.',
        term_downtrend_example: '"This stock has been in a downtrend for two months, making selling on rallies an effective strategy."',
        term_downtrend_related1: 'Uptrend',
        term_downtrend_related2: 'Ranging Market',
        term_downtrend_related3: 'Trendline',
        term_nikkei_title: 'Nikkei Stock Average',
        term_nikkei_desc: 'The Nikkei Stock Average (Nikkei 225) is a stock market index for the Tokyo Stock Exchange, calculated by averaging the prices of 225 representative listed companies. It is a widely used indicator of the overall Japanese stock market.',
        term_nikkei_point1: 'A price-weighted average, where higher-priced stocks have a greater impact.',
        term_nikkei_point2: 'Calculated and published by Nikkei Inc.',
        term_nikkei_point3: 'The constituent stocks are reviewed periodically.',
        term_nikkei_point4: 'It is a target for futures and options trading.',
        term_nikkei_example: '"Following a rise in the U.S. stock market, the Nikkei Stock Average recovered to the ¥29,000 level."',
        term_nikkei_related1: 'TOPIX',
        term_nikkei_related2: 'Dow Average',
        term_nikkei_related3: 'Nikkei Futures',
        term_dividend_title: 'Dividend',
        term_dividend_desc: 'A dividend is a mechanism for a company to distribute a portion of its profits to shareholders in cash. It is a key method of shareholder return and is typically paid once (final) or twice (interim and final) a year.',
        term_dividend_point1: 'The dividend amount is expressed as an amount per share.',
        term_dividend_point2: 'Dividend Yield = (Annual Dividend per Share / Stock Price) x 100 (%).',
        term_dividend_point3: 'Paid to shareholders who are on the company register on the record date.',
        term_dividend_point4: 'Payout Ratio = (Total Dividends / Net Income) x 100 (%), showing the proportion of earnings paid as dividends.',
        term_dividend_example: '"This company pays an annual dividend of ¥60 per share, resulting in a 2% dividend yield at the current stock price of ¥3,000."',
        term_dividend_related1: 'Dividend Yield',
        term_dividend_related2: 'Record Date',
        term_dividend_related3: 'Shareholder Return',
        term_gap_title: 'Window (Gap)',
        term_gap_desc: 'A window (or gap) is a phenomenon where a space appears between the previous day\'s closing price and the current day\'s opening price. There are upward gaps (higher open) and downward gaps (lower open).',
        term_gap_point1: 'Often occurs after major economic news or corporate earnings announcements.',
        term_gap_point2: 'The saying "gaps get filled" suggests the price often returns to that level later.',
        term_gap_point3: 'An upward gap in an uptrend is a bullish sign; a downward gap in a downtrend is a bearish sign.',
        term_gap_point4: 'A large gap can sometimes signal a trend reversal.',
        term_gap_example: '"Following strong earnings, the stock opened with a large upward gap at ¥1,580, up from the previous close of ¥1,500."',
        term_gap_related1: 'Filling the Gap',
        term_gap_related2: 'Market Open',
        term_gap_related3: 'Day-over-Day Change',
        term_ohlc_title: 'OHLC (Open, High, Low, Close)',
        term_ohlc_desc: 'OHLC refers to the four key prices of a stock for a given period (usually a day): the opening, high, low, and closing prices. This is the fundamental data for candlestick charts.',
        term_ohlc_point1: 'Open: The first price traded at the beginning of the period.',
        term_ohlc_point2: 'High: The highest price traded during the period.',
        term_ohlc_point3: 'Low: The lowest price traded during the period.',
        term_ohlc_point4: 'Close: The last price traded at the end of the period (becomes the reference for the next day).',
        term_ohlc_example: '"Today\'s OHLC for Toyota Motor were: Open ¥2,100, High ¥2,150, Low ¥2,080, and Close ¥2,120."',
        term_ohlc_related1: 'Candlestick',
        term_ohlc_related2: 'Market Open',
        term_ohlc_related3: 'Market Close',
        term_candlestick_title: 'Candlestick',
        term_candlestick_desc: 'A candlestick is a chart type used in technical analysis that originated in Japan. It displays the high, low, open, and closing prices for a specific period in a single shape.',
        term_candlestick_point1: 'Body: The rectangular part connecting the open and close prices.',
        term_candlestick_point2: 'Wick (or Shadow): The lines extending from the body to the high and low prices.',
        term_candlestick_point3: 'Bullish (White/Green/Blue): The close is higher than the open (price went up).',
        term_candlestick_point4: 'Bearish (Black/Red): The close is lower than the open (price went down).',
        term_candlestick_point5: 'Various patterns (e.g., Harami, Engulfing, Doji) can indicate market turning points.',
        term_candlestick_example: '"The daily chart shows three consecutive long bullish candlesticks, indicating sustained strong buying pressure."',
        term_candlestick_related1: 'OHLC',
        term_candlestick_related2: 'Bullish Line',
        term_candlestick_related3: 'Bearish Line',
        term_resistance_line_title: 'Resistance Line',
        term_resistance_line_desc: 'A resistance line is a level on a chart where a rising stock price tends to pause or fall back. It is formed by connecting previous highs and is also known as a resistance level.',
        term_resistance_line_point1: 'Formed by connecting past high points.',
        term_resistance_line_point2: 'Selling interest tends to increase as the price approaches a resistance line.',
        term_resistance_line_point3: 'A break above the resistance line suggests a higher probability of further rise.',
        term_resistance_line_point4: 'A former resistance line can become a support line if the price breaks above and then returns to it.',
        term_resistance_line_example: '"The Nikkei Average has strong resistance around ¥30,000, having fallen back from this level twice."',
        term_resistance_line_related1: 'Support Line',
        term_resistance_line_related2: 'Trendline',
        term_resistance_line_related3: 'Breakout',
        term_value_stock_title: 'Value Stock',
        term_value_stock_desc: 'A value stock is a stock that appears to be trading for less than its intrinsic or book value. It is often the target of value investing.',
        term_value_stock_point1: 'PER (Price-to-Earnings ratio) is lower than the industry or market average.',
        term_value_stock_point2: 'PBR (Price-to-Book ratio) is below 1 or lower than the industry average.',
        term_value_stock_point3: 'Dividend yield is higher than the market average.',
        term_value_stock_point4: 'The stock price is undervalued relative to the company\'s growth or earnings potential.',
        term_value_stock_example: '"This bank stock, with a PBR of 0.6x and a 4% dividend yield, shows typical characteristics of a value stock."',
        term_value_stock_related1: 'Growth Stock',
        term_value_stock_related2: 'Value Investing',
        term_value_stock_related3: 'PER',

        // Indicators page
        indicators_title: 'Technical Indicators',
        indicators_subtitle: 'Detailed explanation of major technical indicators',
        indicator_search_placeholder: 'Search indicators'
    }
};

// Language switcher HTML
function createLanguageSwitcher() {
    const switcher = document.createElement('div');
    switcher.id = 'lang-switcher';
    switcher.className = 'fixed top-4 right-4 z-50 bg-white rounded-lg shadow-lg border border-gray-200 p-2';
    switcher.innerHTML = `
        <div class="flex items-center space-x-2">
            <button class="lang-btn ${currentLang === 'ja' ? 'bg-primary text-white' : 'bg-gray-100 text-gray-700'} px-3 py-1 rounded text-sm font-medium transition-colors" data-lang="ja">日本語</button>
            <span class="text-gray-400">|</span>
            <button class="lang-btn ${currentLang === 'en' ? 'bg-primary text-white' : 'bg-gray-100 text-gray-700'} px-3 py-1 rounded text-sm font-medium transition-colors" data-lang="en">English</button>
        </div>
    `;
    
    // Add event listeners
    switcher.querySelectorAll('.lang-btn').forEach(btn => {
        btn.addEventListener('click', function() {
            const lang = this.getAttribute('data-lang');
            switchLanguage(lang);
        });
    });
    
    return switcher;
}

// Switch language function
function switchLanguage(lang) {
    currentLang = lang;
    localStorage.setItem('language', lang);
    
    // Update language switcher buttons
    document.querySelectorAll('.lang-btn').forEach(btn => {
        const btnLang = btn.getAttribute('data-lang');
        if (btnLang === lang) {
            btn.className = 'lang-btn bg-primary text-white px-3 py-1 rounded text-sm font-medium transition-colors';
        } else {
            btn.className = 'lang-btn bg-gray-100 text-gray-700 px-3 py-1 rounded text-sm font-medium transition-colors';
        }
    });
    
    // Update all translatable elements
    document.querySelectorAll('[data-lang]').forEach(element => {
        const key = element.getAttribute('data-lang');
        if (translations[lang][key]) {
            element.textContent = translations[lang][key];
        }
    });
    
    // Update placeholders
    document.querySelectorAll('[data-lang-placeholder]').forEach(element => {
        const key = element.getAttribute('data-lang-placeholder');
        if (translations[lang][key]) {
            element.placeholder = translations[lang][key];
        }
    });
    
    // Trigger custom event for dynamic content
    document.dispatchEvent(new CustomEvent('languageChanged', { detail: { lang } }));
}

// Initialize language system
function initLanguage() {
    // Add language switcher to page
    const switcher = createLanguageSwitcher();
    document.body.appendChild(switcher);
    
    // Apply current language
    switchLanguage(currentLang);
}

// Get translation function
function getTranslation(key, lang = currentLang) {
    return translations[lang][key] || key;
}

// Export functions for use in other scripts
window.initLanguage = initLanguage;
window.switchLanguage = switchLanguage;
window.currentLang = currentLang;
window.translations = translations;
window.getTranslation = getTranslation; 